import type { Metadata } from "next";
import { Fira_Code, Inter } from "next/font/google";
import "@/styles/globals.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const firaCode = Fira_Code({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-fira-code",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} ${inter.className} antialiased`}>
        <Header />
        <main
          id="content"
          className="max-w-screen-xl px-6 w-full mx-auto md:px-24 sm:px-12"
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
